version: '3.8'
services:
  micromix-flask-backend:
    build: ./backend
    network_mode: "host"
    ports:
      - "5000:5000" #host:container
    environment:
      - CLUSTERED_HEATMAP_FRONTEND_URL=http://127.0.0.1:8082/
  micromix-vue-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "7000:80" #host:container


